### ISSUE TITLE
Offset support

### ISSUE THREAD

**Issue by v0od0oChild** [aravindnc/mongoose-aggregate-paginate-v2#11]
Is it possible to use offset just like in [mongoose-paginate-v2](https://github.com/aravindnc/mongoose-paginate-v2) ?

**Comment by aravindnc** [comment]
Can you please explain your requirement @v0od0oChild

**Comment by v0od0oChild** [comment]
mongoose-paginate-v2 allowed queries to use offsets or pages, also returning the used offset value in the meta.
`Model.paginate({ offset, limit }, options)`

However mongoose-aggregate-paginate-v2 doesn't seem to support this anymore.
`Model.aggregatePaginate({ offset, limit }, options)`

**Comment by aravindnc** [comment]
@v0od0oChild mongoose-aggregate-paginate-v2 never had "offset" feature before. So I may need to add it.

**Comment by aravindnc** [comment]
@v0od0oChild Added a patch. Please check and let me know.
