### ISSUE TITLE
no have meta in customLabels same mongoose-paginate-v2

### ISSUE THREAD

**Issue by ngocnv1712** [aravindnc/mongoose-aggregate-paginate-v2#12]
please fix it.

**Comment by aravindnc** [comment]
That is a new feature. I will add it shortly.

**Comment by jayolin** [comment]
Can't seem to find it in the documentation still. Has this been added, @aravindnc?

**Comment by aravindnc** [comment]
@jayolin Sorry, Not done. Will update it this week.

**Comment by aravindnc** [comment]
@jayolin This is done. Please update the version to 1.0.5
