### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by amapy003xamk** [aravindnc/mongoose-aggregate-paginate-v2#27]
Trying to use this package in my project but I get error: "'@types/mongoose-aggregate-paginate-v2@latest' is not in the npm registry. Try `npm install @types/mongoose-aggregate-paginate-v2` if it exists or add a new declaration (.d.ts) file containing `declare module 'mongoose-aggregate-paginate-v2';`" Package installation goes fine but when I import package to my project file this error appears.

When trying `npm install @types/mongoose-aggregate-paginate-v2`, it throws another error: "'@types/mongoose-aggregate-paginate-v2@latest' is not in the npm registry.".

How could I fix this in my project? Installed node version is the latest LTS version if it matters.

**Comment by jessewilliams1** [comment]
++1 on this. Everything else in my app is modern except this

**Comment by aravindnc** [comment]
Sorry I'm not managing the TS version.

**Comment by aravindnc** [comment]
#15

**Comment by aravindnc** [comment]
Added TS defs.
