### ISSUE TITLE
Rename _id fields to id for the result

### ISSUE THREAD

**Issue by awesomelike** [aravindnc/mongoose-aggregate-paginate-v2#30]
In my schema, I have a mongoose virtual field `id` which is equal to `_id`. Generally, it works fine.

However, when I use this library, this virtual field is not working (it is showing `_id`, but the `id` virtual field disappeared).
I have tried `$project` stage in the aggregation pipeline:
```js
{
        $project: {
          id: '$user._id',
          _id: 0
        }
}
``` 
But it is removing all other fields from the response, (only `id` is there).
It is very annoying to explicitly list all the necessary fields with `field1`: 1, `field2`: 1

What is the proper way to rename `_id` field to id while using this library? In other words, how to keep virtuals fields?

**Comment by dennisMeeQ** [comment]
You cannot remove and add a field in the same aggregate stage to my knowledge. I would use these two stages:

```
[
  ...  
  { $addFields: { id: "$_id" } },
  { $project: { _id: 0 } },
  ...
]
```

Have not tested with this library, though.

**Comment by awesomelike** [comment]
Yes, this works
