### ISSUE TITLE
Can groups be paginated separately?

### ISSUE THREAD

**Issue by i-rebel-aj** [aravindnc/mongoose-aggregate-paginate-v2#34]
I have aggregated my collection such that, I am generating documents with `_id` being the grouping condition and I am pushing all the documents that fall into this group in an array. So my final output is like:

```javascript
{_id: 'Student Class1', studentsInThisClass:[ ... ]},
{_id: 'Student Class2', studentsInThisClass:[ ... ]},
...
```
Can I paginate solely on the basis of groups.. my expected output
Groups themselves might be paginated too
```javascript 
   {_id:'Student Class 1', docs:[ .... ]} ,
   {_id:'Student Class 2', docs:[ .... ]} ,
```

**Is it currently supported?**

If my final step in aggregation pipeline is
```javascript
'$group': {
      '_id': '$student.class', 
      'classInfo': {
        '$push': '$$ROOT'
      }
    }
```

**Comment by aravindnc** [comment]
@i-rebel-aj Sorry that is not supported.
