### ISSUE TITLE
cannot set property 'allowdiskuse' of undefined

### ISSUE THREAD

**Issue by MR-omid** [aravindnc/mongoose-aggregate-paginate-v2#35]
we set this option to true and give this error:
`cannot set property 'allowDiskUse' of undefined`
how can i solve this problem?

**Comment by aravindnc** [comment]
Please reopen if issue exists and share more info regarding the issue.

**Comment by joe-icanio** [comment]
```
const response = await Model.aggregatePaginate(
          aggregatePipeline,
          {
            page: page,
            limit: count,
            sort: sortObj,
            allowDiskUse: true,
          }
);

```
TypeError: Cannot set properties of undefined (setting 'allowDiskUse')
    at Aggregate.allowDiskUse (~/node_modules/mongoose/lib/aggregate.js:804:29)

Encountering the same error

**Comment by quangkhait98** [comment]
i have same this issue, the issue have fixed ?
