### ISSUE TITLE
Global options config

### ISSUE THREAD

**Issue by horvathpatrik** [aravindnc/mongoose-aggregate-paginate-v2#37]
The global settings feature is broken, i can't access `aggregatePaginate` object.

`index.js` should contain `module.exports.aggregatePaginate = aggregatePaginate;` to fix it

**Comment by Spown** [comment]
can confirm. also, conventionally plugin config occurs before schema is sent to produce the model.

```js
schema.plugin(aggregatePaginate({...config: here}));
model = db.model('name', schema)
```

**Comment by intenser** [comment]
+1

Any workaround available?

**Comment by aravindnc** [comment]
Fixed in new version.
