### ISSUE TITLE
I can't use mongoose-aggregate-paginate-v2 and mongoose-paginate-v2 in the same project

### ISSUE THREAD

**Issue by CarlValenzuela96** [aravindnc/mongoose-aggregate-paginate-v2#38]
in a part of the project I need to use mongoose-paginate-v2 and it works perfect

![image](https://user-images.githubusercontent.com/13548264/142232207-1e51f4d7-6af8-4763-a9b1-093a1c382fb5.png)

the problem occurs when I try to implement mongoose-aggregate-paginate-v2 in another data model

![image](https://user-images.githubusercontent.com/13548264/142232570-3dcbd2ac-d117-466c-9b1b-f3a47d782612.png)

because when I install it it warns me that in the implementation of the first library (mongoose-paginate-v2) there is no "paginate ()" function

![image](https://user-images.githubusercontent.com/13548264/142231679-c160e6f5-c0a8-488d-be49-ac1b9b1d5354.png)

Is there a way i can use both plugins?

**Comment by aravindnc** [comment]
Is the issue happening with TS version ?

**Comment by CarlValenzuela96** [comment]
Yes, TS version

**Comment by ErickCincoAyon** [comment]
Hermano, encontre la solucion, no es tanto una solucion potente, pero es lo que hay, toca que lo importes directamente asi bro, con el [ var aggregatePaginate = require("mongoose-aggregate-paginate-v2"); ] y ya te va a jalar.

**Comment by aravindnc** [comment]
@ErickCincoAyon English please!

**Comment by ErickCincoAyon** [comment]
Brother, I found the solution, it is not so much a powerful solution, but it is what it is, just import it directly like this bro, with [ var addedPaginate = require("mongoose-aggregate-paginate-v2"); ] and he's going to pull you.

**Comment by ErickCincoAyon** [comment]
![image](https://user-images.githubusercontent.com/55382665/156520029-2f58a1cc-1136-45aa-98cc-0da98b97707f.png)

**Comment by ErickCincoAyon** [comment]
![image](https://user-images.githubusercontent.com/55382665/156520177-810e2ae3-58bd-46ae-a0c8-d386a9318c84.png)

**Comment by ErickCincoAyon** [comment]
And here is one query: 
![image](https://user-images.githubusercontent.com/55382665/156520470-745b0477-30b1-4ed7-82e4-1418772d3530.png)

**Comment by ErickCincoAyon** [comment]
And here is one query: 
![image](https://user-images.githubusercontent.com/55382665/156520535-d1a916f0-e6fd-40ff-a4a8-e5dbb3b11d0b.png)

**Comment by aravindnc** [comment]
@ErickCincoAyon Appreciate it. Thank you.

**Comment by ErickCincoAyon** [comment]
I forgot add this, if u want use the typed of result queries, you should add this 
![image](https://user-images.githubusercontent.com/55382665/156610208-53c82afa-1bbf-4af3-a54a-63898b330fca.png)
into 
![image](https://user-images.githubusercontent.com/55382665/156610416-a47c99cb-dcbe-4aa0-ad87-833f11bbeece.png)

**Comment by samuelpares** [comment]
> And here is one query: ![image](https://user-images.githubusercontent.com/55382665/156520535-d1a916f0-e6fd-40ff-a4a8-e5dbb3b11d0b.png)

How do you declared this.vehicleModel?
I ask because it cant find the aggregatePaginate method, either declaring as Model<Vehicle> or PaginateModel<Vehicle>

**Comment by AlphaTechnolog** [comment]
> This comment could be a bit offtopic, please someone, tell me if i should open another issue or idk, smth like that.

@ErickCincoAyon I think you're using NestJS, correct me if i'm wrong. If you're using it, how did you're injecting the model? I injected it with the next code:
```ts
@InjectModel(PaymentsRequest.name)
private readonly paymentsRequestModel: AggregatePaginateModel<PaymentsRequest>
```
and i'm importing the plugin like you, with require, then calling `Schema.plugin(aggregatePaginate)` inside the entity file, but when i'm trying to call `.aggregatePaginate`, like this:
```ts
const aggregateQuery = this.paymentsRequestModel.aggregate([
	// query...
]);

return await this.paymentsRequestModel.aggregatePaginate(aggregateQuery, paginationData);
```
it throws me an error that says that `.aggregatePaginate` is undefined, i installed `@types/mongoose-aggregate-paginate-v2` and `mongoose-aggregate-paginate-v2` with `yarn`, but seems that it's not working for some reason, or well, looks like the plugin isn't right applied, and in fact, i don't really know why `aggregatePaginate` seems to be undefined, when i'm applying `plugin` to the Schema. I tried too using `.plugin` inside the module, like this:
```ts
import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { MyService } from './my.service';
import { MyController } from './my.controller';
import { PaymentsRequest, PaymentsRequestSchema } from '../payments-requests/entities/payments-request.entity';

const mongooseAggregatePaginate = require('mongoose-aggregate-paginate-v2');

@Module({
	providers: [MyService],
	controllers: [MyController],
	imports: [
		MongooseModule.forFeatureAsync([
			{
				name: PaymentsRequest.name,
				useFactory: () => {
					const schema = PaymentsRequestSchema
					schema.plugin(mongooseAggregatePaginate)
					return schema
				}
			}
		])
	]
})
```
but having the same problem :/

If anyone know what can i'm doing bad, please tell me anyways

**Comment by AnnSamsonenko** [comment]
@AlphaTechnolog Hi, I'm using nestjs also, this import for injected model works as expected: 

`import { AggregatePaginateModel } from 'mongoose';`

and then in service class: 

```
 constructor(
    @InjectModel(User.name) private userModel: AggregatePaginateModel<UserDocument>,
  ) {}
```

**Comment by AlphaTechnolog** [comment]
> @AlphaTechnolog Hi, I'm using nestjs also, this import for injected model works as expected: 
> 
> `import { AggregatePaginateModel } from 'mongoose';`
> 
> and then in service class: 
> 
> ```
>  constructor(
>     @InjectModel(User.name) private userModel: AggregatePaginateModel<UserDocument>,
>   ) {}
> ```

Oh, thank you Anyways, but i ended up implementing the pagination myself lol, I'll try with this the next time then haha

**Comment by jc-granditude** [comment]
Is it possible to use both in the same model?

**Comment by Qionar** [comment]
With nestJS I just use something like that - AggregatePaginateModel<Model> & PaginateModel<Model> to prevent TS throwing any error, not sure that is good one, but it works

**Comment by isadev** [comment]
Yes you can, you only need to add the plugin in the model:

**In your schema**
import paginateWithAgregate from 'mongoose-aggregate-paginate-v2';
...
MyBookSchema.plugin(paginateWithAgregate);

**then in your Model:**
import mongoose, { Document, PaginateModel, AggregatePaginateModel } from "mongoose";
...
export interface MyBookModel extends PaginateModel<MyBookDocument>, AggregatePaginateModel<ConversationDocument> {
...
findBooksWith: (
    this: AggregatePaginateModel<MyBookDocument>,
    param1: string,
    param2: number
  ) => Promise<Pagination>
}

and finally you can use it:
const pipeline = [{ $match: { author: "jhon doe" } }] 
const myAggregate = MyBookModel.aggregate(pipeline);
const queryResults = await MyBookModel.aggregatePaginate(myAggregate, options);
