### ISSUE TITLE
Not paginated the result for $group, $facet, or even $unwind

### ISSUE THREAD

**Issue by mandaputtra** [aravindnc/mongoose-aggregate-paginate-v2#4]
Just tried this aggregation with, `$unwind` `$group` or `$facet` it always serializes the docs to be one.

```js
    Chat.aggregate([
      { $match: { roomId: unique } },
      { $unwind: '$message' },
      { $sort: { 'message.time': -1 } },
      { $group: { _id: "$_id", message: "$message.text" } } 
    ])
```

**Comment by aravindnc** [comment]
@mandaputtra I will review it and get back.

**Comment by mandaputtra** [comment]
Just for info, I get around this issue with `$facet`

```js
// assume that page and limit are query params contains number 
{
  $facet: {
     metadata: [{ $count: 'total' }, { $addFields: { page: page } }],
     data: [
       { $skip: page === 1 ? 0 : (page - 1) * limit },
           { $limit: limit }
      ]}
}
```

**Comment by aravindnc** [comment]
@mandaputtra Glad to hear that.

**Comment by mandaputtra** [comment]
I'll do some test in my free time, and maybe if this was bug ill try to pull request. But that could be a major change. Lest see..

**Comment by aravindnc** [comment]
@mandaputtra Appreciate it. You're awesome!

**Comment by gezimapi** [comment]
hi ,

i am having the same problem .   it always serializes all the docs in the collection one by one not the result in aggregate.

**Comment by mandaputtra** [comment]
@gezimapi I custom paginate it, with $facet. I wrote an articele [here](https://dev.to/mandaputtra/beginner-guide-on-mongodb-aggregate-337g).

It will be a major change if the feature merged,

**Comment by aravindnc** [comment]
Thanks @mandaputtra
