### ISSUE TITLE
Is this library cursor based or page based?

### ISSUE THREAD

**Issue by anuraagy** [aravindnc/mongoose-aggregate-paginate-v2#51]
https://github.com/aravindnc/mongoose-aggregate-paginate-v2/blob/1be8d509a2c298e5d68ebe3369259366e243cf48/lib/mongoose-aggregate-paginate.js#L108

Based on this code, it looks like it's page based. Please let me know if I'm looking at something incorrectly.

**Comment by abdimussa87** [comment]
Is it bad if it's page based?

**Comment by anuraagy** [comment]
There is nothing wrong with it being page based! But, the README lists the library as being cursor based, which would be incorrect?

**Comment by aravindnc** [comment]
Its page based. Updated readme.

**Comment by amitbeck** [comment]
> Its page based. Updated readme.

@aravindnc You should also update the repository's About section and topic

**Comment by aravindnc** [comment]
> > Its page based. Updated readme.
> 
> @aravindnc You should also update the repository's About section and topic

Updated. Thanks for pointing out.
