### ISSUE TITLE
MongoServerError: the $sort key specification must be an object

### ISSUE THREAD

**Issue by sendyputra** [aravindnc/mongoose-aggregate-paginate-v2#59]
I got error if sort string

![Screenshot 2024-06-27 at 12 05 48](https://github.com/aravindnc/mongoose-aggregate-paginate-v2/assets/310664/79fc69db-f974-4273-8f04-4ca041ce9144)

**Comment by aravindnc** [comment]
@sendyputra Can you may pass it as object instead.

**Comment by aravindnc** [comment]
Please reopen if the issue exists in object sort.
