### ISSUE TITLE
Global options config like `mongoose-paginate-v2`

### ISSUE THREAD

**Issue by wxs77577** [aravindnc/mongoose-aggregate-paginate-v2#6]
Could you add global options config like `mongoose-paginate-v2` please?

#### Set custom default options for all queries

config.js:

```javascript
var mongoosePaginate = require('mongoose-paginate-v2');

mongoosePaginate.paginate.options = { 
  lean:  true,
  limit: 20
};
```

**Comment by aravindnc** [comment]
@wxs77577 Sorry for the delay. I will add an update this week.
