### ISSUE TITLE
Option to disable pagination

### ISSUE THREAD

**Issue by WaveMeUp** [aravindnc/mongoose-aggregate-paginate-v2#7]
Hello!
Thanks for this library.
Can you please provide functionality for disabling pagination like you did for mongoose-paginate-v2?

Thank you.

**Comment by aravindnc** [comment]
@WaveMeUp Sure. I will add a patch this week.
Thanks.

**Comment by aravindnc** [comment]
@WaveMeUp Please use option: {pagination: false}

**Comment by brunachamon** [comment]
> {pagination: false}

Hi @aravindnc ,

I'm trying to set pagination to false and I get this error:

> "message": "Aggregate has empty pipeline"

How can I use this option?
